import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Menu, Search } from "lucide-react";
import { categories } from "./data";
import Link from "next/link";

const helvetica = localFont({
  src: "./fonts/HelveticaNeueLTPro-Md.woff",
  variable: "--font-helvetica",
});
const helveticaRoman = localFont({
  src: "./fonts/HelveticaNeueLTPro-Roman.woff",
  variable: "--font-helvetica-roman",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${helvetica.variable} ${helveticaRoman.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          <header className="flex items-center justify-between p-4 border-b-2 border-yellow-300">
            <div className="flex items-center space-x-4">
              <Button variant="ghost" size="icon">
                <Menu className="h-6 w-6" />
                <span className="sr-only">Toggle menu</span>
              </Button>
              <Link href="/" className="text-2xl font-bold">
                McMaster-Next
              </Link>
            </div>
            <div className="flex items-center space-x-4">
              <div className="relative">
                <Search className="absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" />
                <Input placeholder="Search" className="pl-8 w-[300px]" />
              </div>
              <Button variant="ghost">ORDER</Button>
              <Button variant="ghost">ORDER HISTORY</Button>
            </div>
          </header>
          <div className="flex flex-1 font-helvetica-roman">
            <aside className="w-64 border-r border-gray-400 p-4 hidden md:block">
              <h2 className="text-sm border-b border-green-800 text-green-900 font-semibold">
                Choose a Category
              </h2>
              <ul className="">
                {categories.map((category) => (
                  <li key={category} className="hover:bg-yellow-200 pb-2 group">
                    <a
                      href="#"
                      className="text-xs group-hover:underline text-gray-800"
                    >
                      {category}
                    </a>
                  </li>
                ))}
              </ul>
            </aside>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
